<?php 
  if (defined('RUNNING_FROM_ROOT')) {
    $this->plugin('basePath')->setBasePath($this->basePath().'/public');
  } ?>
<?= $this->doctype() ?>
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Weather App</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Le styles -->
    <?= $this->headLink([
      'rel' => 'shortcut icon',
      'type' => 'image/vnd.microsoft.icon',
      'href' => $this->basePath() . '/img/favicon.ico'
      ])
      ->prependStylesheet($this->basePath('assets/css/style.css')); 
      ?>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="<?= $this->basePath(); ?>/assets/js/moment.js"></script>
    <script type="text/javascript">
      var base_url = "<?= $this->url('home'); ?>";
      var basePath = "<?= $this->basePath(); ?>";
    </script>
    <script src="<?= $this->basePath(); ?>/assets/js/main.js"></script>
  </head>
  <body>
    <div class="container">
      <div class="main-section">
        <div class="main-heading">
          <div class="card">
            <div class="card-body">
              <div class="text-center">
                <img src="<?= $this->basePath('assets/images/ow.jpg') ?>" class="rounded me-2" alt="Weather Forecast" width="50" height="40">
                <strong>Welcome to weather forecast application!</strong>
              </div>
            </div>
          </div>
        </div>
        <div class="main-content">
          <div class="card">
            <div class="card-body">
              <div class="p-3">
                  <div class="card">
                  <div class="card-body">
                    <b>Note:</b>
                    <div>1. Please note that 'One Call 3.0' requires a separate subscription to the One Call by Call plan. Learn more here <a href="https://openweathermap.org/price" target="_blank">https://openweathermap.org/price</a>.</div>
                    <div>2. As we do not have any active <b>paid subscription</b> at the moment, so we have implemented api version 2.5, which provides below 2 apis for free of cost.</div>
                    <div>a) Current Weather Data <span class="ms-3">b) 5 Day / 3 Hour Forecast</span></div>
                  </div>
              </div>
              </div>
              
              <div class="mb-4 p-3">
                <div class="text-center mb-3">
                <b>You can search for any location (for example London, England, GB) and get a weather forecast for that location.</b>
                </div>
                <div class="card main-card">
                  <div class="card-body">
                    <div class="ps-5 pe-5 mt-2">
                      <label for="location" class="form-label"><strong>Enter Location:</strong></label>
                      <div class="input-group">
                        <input type="text" class="form-control" id="location" placeholder="Location" name="location" data-lat="" data-lon="">
                      </div>
                      <div id="suggesstion-box"></div>
                      <div class="mt-4 mb-4 text-center">
                        <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                          <input type="radio" class="btn-check weather_for" name="weather_for" id="weather_for1" autocomplete="off" checked value="Current Weather">
                          <label class="btn btn-outline-danger" for="weather_for1">Current Weather</label>
                          <input type="radio" class="btn-check weather_for" name="weather_for" id="weather_for2" autocomplete="off" value="Next 24 Hours">
                          <label class="btn btn-outline-danger" for="weather_for2">Next 24 Hours</label>
                          <input type="radio" class="btn-check weather_for" name="weather_for" id="weather_for3" autocomplete="off" value="Next 7 Days">
                          <label class="btn btn-outline-danger" for="weather_for3">Next 7 Days</label>
                        </div>
                      </div>
                    </div>
                    <div class="ps-5 pe-5">
                      <div id="spinner">
                        <img id="spinner-img" src="<?= $this->basePath('assets/images/orange-loader.gif') ?>">
                      </div>
                      <div id="current-weather-section">
                        <div class="table-heading">Current Weather</div>
                        <table class="table table-bordered" id="current-weather-table">
                          <tbody>
                            <tr>
                              <td class="fw-bold">Weather Description</td>
                              <td><span id="weather-description"></span></td>
                            </tr>
                            <tr>
                              <td class="fw-bold">Current Temperature</td>
                              <td><span id="current-temperature"></span></td>
                            </tr>
                            <tr>
                              <td class="fw-bold">Feels Like</td>
                              <td><span id="feels-like"></span></td>
                            </tr>
                            <tr>
                              <td class="fw-bold">Humidity</td>
                              <td><span id="humidity"></span></td>
                            </tr>
                          </tbody>
                        </table>
                      </div>
                      <div id="next-24-hours-section">
                        <div class="table-heading">Next 24 Hours</div>
                        <table class="table table-bordered" id="next-24-hours-table">
                          <thead>
                            <tr>
                              <th class="text-center">Hour <small>(Timezone: UTC)</small></th>
                              <th class="text-center">Weather</th>
                              <th class="text-center">Temperature</th>
                            </tr>
                          </thead>
                          <tbody id="next-24-hours-table-tbody">
                          </tbody>
                        </table>
                      </div>
                      <div id="next-7-days-section">
                        <div class="table-heading">Next 7 Days</div>
                        <table class="table table-bordered" id="next-7-days-table">
                          <thead>
                            <tr>
                              <th class="text-center">Hour <small>(Timezone: UTC)</small></th>
                              <th class="text-center">Weather</th>
                              <th class="text-center">Temperature</th>
                            </tr>
                          </thead>
                          <tbody id="next-7-days-table-tbody">
                          </tbody>
                        </table>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>